version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  seqwall:
    image: ghcr.io/realkarych/seqwall:latest
    platform: linux/amd64
    depends_on:
      db_test:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_test:5432/${POSTGRES_DB}?sslmode=disable
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
    entrypoint:
      - sh
      - -c
      - |
        apk add --no-cache curl &&
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xz &&
        mv migrate /usr/local/bin/migrate &&
        chmod +x /usr/local/bin/migrate &&
        exec seqwall "$@"
      - --
    command:
      - staircase
      - --postgres-url
      - postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_test:5432/${POSTGRES_DB}?sslmode=disable
      - --migrations-path
      - /migrations
      - --migrations-extension
      - .up.sql
      - --upgrade
      - /scripts/ci-up-one.sh
      - --downgrade
      - /scripts/ci-down-one.sh

  migrator:
    image: migrate/migrate
    depends_on:
      seqwall:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]

  seeder:
    image: postgres:15
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./seeds:/seeds
    entrypoint: >
      bash -e -c "
      if [ \"$APP_ENV\" = \"prod\" ]; then
        echo 'Seeding запрещён в prod';
        exit 1;
      fi;

      echo 'Start seeding...';

      psql -v ON_ERROR_STOP=1 -h db -U $POSTGRES_USER -d $POSTGRES_DB -f /seeds/001_users_roles.seed.sql &&
      psql -v ON_ERROR_STOP=1 -h db -U $POSTGRES_USER -d $POSTGRES_DB -f /seeds/002_addresses_sellers.seed.sql &&
      psql -v ON_ERROR_STOP=1 -h db -U $POSTGRES_USER -d $POSTGRES_DB -f /seeds/003_catalog.seed.sql &&
      psql -v ON_ERROR_STOP=1 -h db -U $POSTGRES_USER -d $POSTGRES_DB -f /seeds/004_inventory_cart.seed.sql &&
      psql -v ON_ERROR_STOP=1 -h db -U $POSTGRES_USER -d $POSTGRES_DB -f /seeds/005_orders.seed.sql;

      echo 'Seeding done';
      "
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      DATA_SOURCE_NAME: "postgresql://${METRICS_USER}:${METRICS_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE}
    ports:
      - "9000:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data

  backup:
    build:
      context: ./backup
    container_name: backup
    depends_on:
      - db
      - minio
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BACKUP_ACCESS_KEY: ${MINIO_BACKUP_ACCESS_KEY}
      MINIO_BACKUP_SECRET_KEY: ${MINIO_BACKUP_SECRET_KEY}

      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      BACKUP_RETENTION_COUNT: ${BACKUP_RETENTION_COUNT}
      BUCKET_BACKUP_NAME: ${BUCKET_BACKUP_NAME}
    volumes:
      - backup_state:/state

  backup_exporter:
    build:
      context: ./backup-exporter
    container_name: backup_exporter
    depends_on:
      - backup
    ports:
      - "8000:8000"
    volumes:
      - backup_state:/state:ro

  prometheus:
    image: prom/prometheus:latest
    restart: always
    depends_on:
      - postgres_exporter
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    env_file:
     - .env
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:
  minio_data:
  backup_state: