global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: minio
    metrics_path: /minio/metrics/v3
    static_configs:
      - targets: ["minio:9000"]

  - job_name: backup_exporter
    static_configs:
      - targets: ["backup_exporter:8000"]

  - job_name: workload
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["workload:8080"]
